# Model run parameters
data_dir: '/Users/yuezi/Google Drive/LAB/NYS_energy_system/two_nodes_model_comparison/input_data'
results_dir: '/Users/yuezi/Google Drive/LAB/NYS_energy_system/two_nodes_model_comparison/model_results'

num_hours: 8784
i_rate: 0.07

# SOLAR
solar_cost_mw: 788000
solar_cost_om_mw_yr: 22020
n_year_solar: 30

# WIND
wind_cost_mw: 1095000
wind_cost_om_mw_yr: 47470
n_year_wind: 30

#NGCC
gt_cost_mw: 982000
gt_cost_om_mw_yr: 11110
gt_cost_om_mwh: 3.54
gt_cost_fuel_mwh: 19.1
gt_effi: 0.54
n_year_gt: 20

# NUCLEAR
nuc_cost_mw: 1027000
nuc_cost_om_mw_yr: 101280
nuc_cost_om_mwh: 2.32
nuc_cost_fuel_mwh: 7.5
nuc_effi: 0.33
n_year_nuc: 40

# BATTERY
bat_cost_mwh: 26000
bat_effi: 0.9
bat_decay: 1.14e-6
bat_etp: 6.008
n_year_bat: 10
bat_st_end_mwh: 0.5

# TRANSMISSION
trans_cost_mw: 750000
trans_losses: 0.01
n_year_trans: 30

# Gurobi solver parameters
feasibility_tol: 0.01
solver_method: -1